### ISSUE TITLE
not found FtpCredendtials.cs

### ISSUE THREAD

**Issue by orzMaster** [r3peat/R3p.BDO#16]

**Comment by Acen** [comment]
Fast catch.

You might be interested in seeing https://github.com/r3peat/R3p.BDO/issues/12 where @netzulo is attempting pushing the distribution of updates onto Mega.

**Comment by netzulo** [comment]
hi @orzMaster , your answer it's here , at README

https://github.com/r3peat/R3p.BDO#how-to-compile-sources

## How to compile sources?

* Recreate classes with ftp credentials because are removed from **r3p.bdo.testconsole** + **r3p.bdo.guiloader**
* To make this work use ur own ftp with ur own credentials or just disable these features
